block-place-cooldown-enabled: true
block-place-cooldown-actionlimit: 5
block-place-cooldown-duration: 10
block-place-exempt-blocks: None

block-break-cooldown-enabled: true
block-break-cooldown-actionlimit: 5
block-break-cooldown-duration: 10
block-break-exempt-blocks: None

notify-chat-on-remaining-uses: true
notify-chat-on-cooldown-completion: true
play-sound-on-cooldown-completion: true