name: ActionCooldown
version: '${project.version}'
main: me.hunterttp.actioncooldown.MainClass
api-version: 1.18
authors: [ HunterTTP ]
commands:
  ActionCooldown:
    description: Command to alter ActionCooldown limits, cd durations, etc
    usage: /ActionCooldown